# Generated by Django 4.0.6 on 2022-07-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=120, verbose_name='Persons email address')),
                ('message', models.TextField(max_length=1200)),
                ('viewed', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'verbose_name': 'Contact request',
                'verbose_name_plural': 'Contact requests',
            },
        ),
    ]
